### ISSUE TITLE
Support subclassing SKYRecord in iOS and Android SDK

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#112]
# Description

In most similar framework, users can use subclassing to create Record class, so developers can access data of a record as properties instead of `ObjectForKey` or something like `object[@"properties"]`.

The advantages are:
* Support autocomplete when accessing attributes.
* Some developers really want to organise business logic along model class.

# API Design

### Declaration
Parse similar support are:

```
class Armor : PFObject, PFSubclassing {
  override class func initialize() {
    struct Static {
      static var onceToken : dispatch_once_t = 0;
    }
    dispatch_once(&Static.onceToken) {
      self.registerSubclass()
    }
  }

  static func parseClassName() -> String {
    return "Armor"
  }
}
```

or Realm:

```
class Dog: Object {
    @objc dynamic var name = ""
    @objc dynamic var age = 0
}
class Person: Object {
    @objc dynamic var name = ""
    @objc dynamic var picture: Data? = nil // optionals supported
    let dogs = List<Dog>()
}

let puppies = realm.objects(Dog.self).filter("age < 2")
```

### SKYReference improvement

Making sure subclassed Record object can be used instead of `skygear.Reference` or `SKYReference` for query in JS / iOS / Android

### SKYQuery improvement

Improve SKYQuery (iOS, but also applies to JS / Android if possible) as:
* Don't have to type the string for SKYQuery (so instead of `SKYQuery(recordType: "Note", predicate: p)`, do `SKYQuery(Note, predicate: p)`
* Avoid casting of query records if language support (I was told Swift support) at least.

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by cheungpat** [comment]
Um... the Parse code seems to be registering a class during app init so that the frameworks knows which class to use when creating a record for the record data. Looks like we are one step towards having the developer to define their model class for those who need it : )

**Comment by louischan-oursky** [comment]
A skygear record literally is a representation of the underlying database table. However, this level of abstraction normally is too low for application usage.

Let's consider we are building chat app and we have the following kinds of message.

1. Text Message
2. Image Message
3. Voice Message
4. Location Message

A typical representation of message in database level would be

```sql
CREATE TABLE message (
  id TEXT PRIMARY KEY,
  text TEXT,
  image_id TEXT,
  voice_id TEXT,
  location POINT
)
```

A message must be of one of the kind, so only exactly one of `text`, `image_id`, `voice_id` and `location` is non-null.

In modern programming languages (such as Swift and Kotlin), you can represent this type of information with sum type

For example in Swift, we can encode message as

```swift
enum MessageContent {
    case text(String)
    case image(URL)
    case voice(URL)
    case location(CLLocation)
}
struct Message {
    let id: String
    let content: MessageContent
}
```

Then whenever we have a `Message`, the type system ensures that it must be a message with known kind of content. Also, `id` and `content` are immutable.

Personally I do not use skygear record directly when implementing the business logic. The reason is simple. We cannot leverage the type system offered by those modern programming languages to enfoce invarants of custom data types. Enforcing invarants prevent bugs.

Being able to subclass skygear record may encourage people to use skygear record directly.

**Comment by chpapa** [comment]
@louischan I have zero experience with Kotlin and Swift. If we don't do subclass and use struct or enum type like the above, is it good enough and can still encourage people to "use Skygear record directly?" (not quite sure what it meant actually)

**Comment by louischan-oursky** [comment]
My comment is based on the concept of [making illegal states unrepresentable](https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/). A skygear record exposes the raw database representation of the data thus it is hard to enforce invariants. Subclassing it inherits this disadvantage.
