### ISSUE TITLE
[CMS] Role models and policy setting spec

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#152]
# Description

**Add 2-3 sentence description of your feature**

# Portal Design

**Remove this section if the feature have no Portal**

## Portal Features

**Put Portal Feature List here**

# API Design

**Remove this section if the feature have no API**

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
I'm imaging applying a policy-based ACL for the CMS, it could be something like:

## Should support in this phase

### Record based access
action: CREATE / READ / UPDATE / DELETE
resources: `resources:entity:<entity name>`

(reason why it is `entity`, not `record type`, is because the ACL should reflect the entity defined in the CMS's config file, not each record class in Skygear DB)

e.g.
* Allow listing of records, and create new records
action: `create|read`
resources: `resources:entity:jobs`

### Permission to access certain functions
action: (CRUD, or sth else is better?)
resources: `resources:push`

Set a user to disallow access to `resources:push` will disable the push section

## Support in future?

* `resources:entity:<entity name>:<ids>:<field name>`
* `resources:push:<user ids>`
    * actions:
        * SEND: send push notifications
        * LIST: list all push notifications sent to the users
* `resources:user-management:group:<group ids>`
* `resources:user-management:users:<user ids>`
    * actions
        * Block: block users
        * Edit: edit profile
        * RSPassword: reset password
        * etc...

**Comment by chpapa** [comment]
Could consider using sth like https://github.com/ory/ladon or https://github.com/casbin/casbin

**Comment by carmenlau** [comment]
This spec needs further discussion and we planned to do a simple version of user management first. Will remove it from the milestone planning.

CMS basic user management https://github.com/SkygearIO/features/blob/4116caf42b6d5225176025c300c6f63cc90e1a6a/features/165-cms-basic-user-management/api.md
