### ISSUE TITLE
Fix consistent issue of error.message vs error.error.message

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#190]
# Description

Currently due to how lambda works, error message are sometime accessible via `error.message` some time `error.error.message`

We should make it consistent to `error.message`

# API Design

TODO:
* List all APIs that have `error.error.message`

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by limouren** [comment]
If we are going to break API, I will prefer all errors to be `Error` instead of an dictionary.

**Comment by cheungpat** [comment]
yea, should have used `SkygearError` instead of rejecting with an object.

**Comment by carmenlau** [comment]
Remove `require/spec` label, I think it is clear that we expected that all the error should return `SkygearError` object so no `error.error.message`. Please find the checklist below. 

- [ ] For JS SDK, Core API should return the correct Error object already, only lambda has this problem, need double check. Update JS SDK when calling lambda with error, should reject with `SkygearError` instead of an object
- [ ] For iOS SDK, check SDK api is returning correct error object
- [ ] For Android SDK, check SDK api is returning correct error object

**Comment by carmenlau** [comment]
In all three platform we had the Error object already. I thought we are good with the Error object format and this issue is talking about the not all the error callback use the `SkygearError` object? We had `info` field for extra info in all 3 platform error object, for `createDistinctConversation ` case we can put the existing conversation object in the info field.

Btw, I talked with @limouren. In the JS SDK, not only lambda has the problem. When saving record, if there is only one record, the promise will be rejected if save is fail. But when user save multiple records and some of them are fail in non-atomic save, the promise is resolved. It makes user difficult to handle the error. In JS, we can only resolve or reject the promise, we don't have something like `onPartiallySaveSuccess`. Maybe we need to have a discussion on how we handle record saving error case.

**Comment by chpapa** [comment]
@carmenlau understood. My major concern is if it is a breaking change, let's try to make it happen for once only. It seems one thing is:

1. JS SDK onPartiallySaveSuccess, how to handle it in Promise
2. Make sure the info field can handle the `createDistinctConversation` case beautifully.

**Comment by carmenlau** [comment]
1. Since we cannot do `onPartiallySaveSuccess` in JS, so we need to decide resolve or reject in partially save case. This part we need to discuss.
2. IMO, we can have `CreateConversationError` which extents the original error and have method like `getExistingConversation` that will case the data in info to `Conversation` object. Of cause we can further review if the existing Error good enough to handle those cases.

Added back the `require/spec` label. Items we want to cover in the spec:

- Collect use cases and review the existing Error object
- Record save partially success handling

When working on
- Review all the api should use the Error object instead of plain object, specifically for JS

**Comment by chpapa** [comment]
@carmenlau is it still relevant for Skygear NEXT? If yes I'm leaving it at Auth to make sure we fixed it.
