### ISSUE TITLE
database _id use uuid instead of text

### ISSUE THREAD

**Issue by hidden-dimensions** [SkygearIO/features#209]
# Description

PgSQL 9.1+ supports `uuid` datatype [ref](https://www.postgresql.org/docs/9.1/static/datatype-uuid.html) which provide better performance over `text`, as `text` field would require going thru collation rules [ref](https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439).

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

This might be compatible breaking as the current field is declared as free text. Chaning to `uuid` require the field to be conform to specific string format (RFC 4122, ISO/IEC 9834-8:2005).

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
Recap some discussions from Slack:

1. Skygear original design was to allow text other than UUID as _id for each Skygear Records, developers believe it is more flexible. It just happens Skygear SDK would fill UUID if _id is not specified.
2. There is some concern about if it is a good design, so this issue is valid only if we make the changes of what _id is.
