### ISSUE TITLE
Skygear server multiple master support

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#230]
# Description

It should replace the current master/slave architecture by:
* Removing master vs slave
* Support pubsub cluster
* Support multiple Skygear Server connects with a single PostgreSQL DB endpoint

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
Copy from #236:

> In skygear-server .env there is a config option: SLAVE intended to disable certain features when multiple running server instances. However such options make deployment non-trivial and also create single point of failure. Suggest to introduce a auto mechanism like voting or even a db atomic lock to select a master to run those "single operations", and re-select periodically / have keep-alive to handle machine down.

**Comment by hidden-dimensions** [comment]
I'm working on APNS lately and found that when using token (instead of cert), there is restriction of one renewal within 20 minutes. This mean for un-coordinated multi-master setup, only one of them can connect to APNS. So when we design multi-master setup, we should either 1) use cert instead or 2) make some coordination for renewing access token.
