### ISSUE TITLE
lightweight py-skygear docker image

### ISSUE THREAD

**Issue by hidden-dimensions** [SkygearIO/features#233]
# Description

`py-skygear:canary` is base on `python:3.6` which in turns based on `buildpack-deps:stretch` and contains a lot of development tools like gcc, ruby, autotool, and lots of libraries which might not be needed. The image is on 900MB mark.

We should consider switch to (or provide additional) lightweight base image like `alphine`, [someone has made a python 3.6 image as small as 61MB](https://hub.docker.com/r/frolvlad/alpine-python3/).

Developer can still opt to install additional tools on his final build stage.

## Scenario

Small image means faster deploy & startup time.

**Comment by cheungpat** [comment]
The official python image on alpine `python:3.6.5-alpine3.6` is 87MB large. You are right it is small because it left out a lot of the development tools. However, the development tools (also known as build-tools or python-dev) are required to install some common python libraries.

For example it is not easy to install bcrypt on this image.

``` shell
$ docker run --rm -it python:3.6.5-alpine3.6 pip install bcrypt
Collecting bcrypt
  Downloading https://files.pythonhosted.org/packages/f3/ec/bb6b384b5134fd881b91b6aa3a88ccddaad0103857760711a5ab8c799358/bcrypt-3.1.4.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 4.1MB/s
Collecting cffi>=1.1 (from bcrypt)
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
    100% |████████████████████████████████| 440kB 7.5MB/s
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5i7tsu3w/cffi/
```

To install `bcrypt`, we need the build tools, which balloons the image to a much bigger size.

The debian base image is chosen also because it is more compatible with prebuilt python packages like scipy. Prebuilt python packages require manylinux support, which isn’t available on alpine linux.

I am open to providing a much smaller Docker image footprint, and I am happy to make it the default. However, doing so will also make it more difficult for novice users to install their dependencies.
