### ISSUE TITLE
Skygear Auth 2.0

### ISSUE THREAD

**Issue by kaojohnny** [SkygearIO/features#256]
# Description

This feature issue is about porting Auth to the new Skygear Next platform.

# Open Questions

- In skygear next, how to update a user's auth info and user profile? 
- In skygear next, how does current user access his own auth info, e.x. last login at, last seen at, disabled state, roles, etc.
- In skygear next, how to access other user's auth info and user profile?

# Related Issues

- Server Issues
SkygearIO/skygear-server#878
SkygearIO/skygear-server#880
SkygearIO/skygear-server#881
SkygearIO/skygear-server#882
SkygearIO/skygear-server#883
SkygearIO/skygear-server#887
SkygearIO/skygear-server#874
SkygearIO/skygear-server#835
SkygearIO/skygear-server#818
SkygearIO/skygear-server#820
SkygearIO/skygear-server#876
SkygearIO/skygear-server#877
SkygearIO/skygear-server#879
- Client Issues
- Guides Issues

**Comment by kaojohnny** [comment]
https://oursky.quip.com/ewfGAfyodkb0

**Comment by chpapa** [comment]
Note from Meeting @kaojohnny 

We will properly need to re-design it since we removed Record Gear in the release, the design shall aim at providing one-way (or even two-way?) sync for auth data, and decide the following:

1. Are we going to provide one-way or two-way sync for auth data?
2. What are the auth data we will need to sync for user's access and the format? (Presume it is SQL first...)
3. Consider the design for syncing auth data to single (and multiple DBs) in future, that might include SQL or non-SQL...

**Comment by chpapa** [comment]
Note from Meeting for new scope:

We will probably need to re-design the whole experience of how auth is used since we removed Record Gear in the release.

There will be two (three?) main ways for users to interact with auth:

1. Client SDK
2. (optional?) SDK for Cloud Functions / gRPC or api call for Cloud Functions
3. Access database sync by auth gear to read (or write?) data

Major considerations:
1. List out possible use cases regarding current auth session / manipulating other users' auth data
2. Determine we will provide one-way or two-way sync for auth data and how? (e.g. One-way sync meant users can "read" all user's disabled status from CF, two-way sync meant users can "read" and "change" all other user's disabled status from CF.)
3. What are the auth data (DB schema) and APIs good enough to satisfy use cases in 1
4. Consider the one-way/two-way sync need to support multiple DB vendors in future.

**Comment by chpapa** [comment]
When we re-design and publish the first Skygear Auth in NEXT, I think we should also make sure:

* "Fix consistent issue of error.message vs error.error.message" #190 is fixed on Client SDK
* Remove "admin" role which is unclear #131 
* Fix the problem of Android SDK need sync functions #111 
* Have proper hooks to Cloud Functions #101 
* Have proper functions for Cloud Functions, e.g. #106

**Comment by chpapa** [comment]
Rename the issue and description
