### ISSUE TITLE
Support push notification without login

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#260]
# Description

Currently, user can only register push notification after login. So if the app need to support push before user login, they must login anonymously which is inconvenient.

## Scenario
Example use case: App may want to send board cast notifications to all the devices.

**Comment by chpapa** [comment]
@carmenlau I am not sure if this should be implemented. Because the rest of skygear basically don't work if user was not sign up anonymously.

I think you are creating this for the client of W** P**?

Instead I think #259 is the right solution for them, we should make 259 works so they can use anonymous user for each session. Maybe a boolean flag to indicate if the user is anonymous too. Or else we will need to make rest of skygear api handle unlogged in users.

On the other hand, I think we should have stronger devices support for users.

**Comment by carmenlau** [comment]
Yes, this issue is created for WP project. Add more detail here, so we can think more when we update this feature in next.

Support upgrade anonymous user to normal user is good feature, but seems cannot solve this problem completely. If user logout user A, then login user B. Before user login user B, we need to register token for push too, but no new user signup in this flow. Maybe we need some mechanism to house keep those not used anonymous users? 

Another result that the project doesn't want to use anonymous user, they have a program to sync the user table to another db. They only want to sync the "real" user to their db, and there is no obvious way to identify anonymous user records in current skygear server. Maybe adding a boolean flag can help.

**Comment by chpapa** [comment]
Included this as a consideration factor in #262
