### ISSUE TITLE
Support forgot password without requiring user login with email

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/features#298]
# Description

Auth gear supports forgot password without requiring user to have `email` as one of the login ID key.

The idea comes from a recent change in auth data to login ID, that we are going to implement a meaningless login ID. (https://github.com/SkygearIO/features/pull/254)

As reference, the current implementation requires login ID to be `email` to match the user when calling forgot password api.

# Scenario

- Applications do not require user to login with email, e.g. login with username, and need to have forgot password feature.
- (Depending on how we implement login with compound key) Applications require email as one of the keys to login, and need to have forgot password feature.

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
p.s. Put back the feature issue template.

I think the issue here is what kind of forgot password mechanism we support?

Currently we have: `forgotPassword(email: String)`, with our new LoginID implementation, maybe we should have:
1. `forgotPasswordByEmail(email: String)` to match ANY loginIDs, or
1. `forgotPasswordByEmail(loginIDkey: String, email:String)`

Option 1 seems make more sense.

And then we may have more API for forgotPassword, e.g.:

* `forgotPasswordBySMS(phone: String)`
* `forgotPasswordByEmailWithSecurityQuestions(email: String)` // obviously just want to compliance with OWASP MASVS L2
* `forgotPasswordByEmailWith2FA(email: String)`
* etc?

Is that what @Steven-Chan is thinking about?

**Comment by Steven-Chan** [comment]
@chpapa 

Didn't think of using loginID when calling forgot password api. It makes me think we can further break down the feature to support more scenario.

---

So when developer calls forgot password api, basically, the api is telling the server two things:

- who has forgotten password, i.e. user query
- how to let the user restore its password

So, in the most naive way, to design the api, we would have `forgotPassword(userQuery, how)`, or as shown in your comment `forgotPasswordBy<how>(userQuery)`.

The original `forgotPassword(email)` has combined both param to one with `email`, i.e. find a user by email and send email to let the user restore its password.

On the other hand, we can have `forgotPasswordByEmail(loginIDKey, loginID)`, i.e. find a user by login ID (whatever key the application use for user login) and send email to let the user restore its password.

The same idea can be applied to the API example you have listed,

- `forgotPasswordBySMS(phone)` / `forgotPasswordBySMS(loginIDKey, loginID)`
- `forgotPasswordByEmailWithSecurityQuestions(email)` / `forgotPasswordByEmailWithSecurityQuestions(loginIDKey, loginID)`
- `forgotPasswordByEmailWith2FA(email)` / `forgotPasswordByEmailWith2FA(loginIDKey, loginID)`
