### ISSUE TITLE
Legacy of `defaultContainer` in JS SDK?

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#356]
## Description

Notice that currently all JS SDK starts with `skygear.defaultContainer`, something like that.

e.g. `skygear.defaultContainer.auth.signup`

The `defaultContainer` sounds like an alien to new users, is it really better to have it instead of simply make it `skygear.auth.signup`?

# Related Issues

- Client Issues

**Comment by chpapa** [comment]
@carmenlau @louischan-oursky wanna draw your attention to it...

**Comment by louischan-oursky** [comment]
It is a problem of how to organize exports in different module systems.

Currently JavaScript has 3 major module systems.

### Script Tag

Strictly speaking it is not a module system. When you include a script tag, for example, `<script src="http://example/my-lib.js"`, the script will pollute the global namespace with a name. In our case, our script bundle will introduce `skygear` into the global namespace.

### CommonJS

It is the most common module system before ES2015 module. The user writes

```
const lib = require("my-lib");
```

The export is always a single value.

### ES2015 module

This is the standard module system. The difference from CommonJS is that ES2015 module has default export and named exports

```typescript
// Import the default export
import skygear from "@skygear/web";
// import the default export explicitly
import { default as skygear } from "@skygear/web";
// import the export named "SkygearError"
import { SkygearError } from "@skygear/web";
```

---

In order to normalize the difference between 3 different module systems. I made a decision to not using default export in ES2015 module. Therefore, the developer must always use named imports.

When the developer is using script tag, they write

```javascript
skygear.defaultContainer.auth;
``` 

When the developer is using commonjs, they write

```javascript
const skygear = require("@skygear/web");
skygear.defaultContainer.auth;
```

When the developer is using ES2015 module, they write

```typescript
import { defaultContainer } from "@skygear/web";
defaultContainer.auth;
```

In all cases, the thing `@skygear/web` works like a namespace that the developer can retrieve things they want to use.

---

If we allow default export in ES2015, then the behavior is very confusing to JavaScript beginners.

```typescript
import skygear from "@skygear/web";
skygear.auth // works
skygear.SkygearError // undefined
```

**Comment by louischan-oursky** [comment]
The issue https://github.com/SkygearIO/skygear-SDK-JS/issues/519

**Comment by chpapa** [comment]
Closing it since @louischan-oursky have decided.
